import 'model.dart';

final List<MealPlan> mealPlans = [
  MealPlan(
    title: 'Higher Body Fat Meal Plan',
    description: 'Lower-calorie, high-protein, and moderate-carb meals.',
    imageUrl: 'https://lh3.googleusercontent.com/1GrUGBrr6T9vi2azmvq6SHmbqeSPlD1sb4VlyM6IHTeFPsTcBdDc6F6YrZk5YnfB744XdShDrjq7BitlPOE5fHxyQ8RUKAbz-5-3gAI=rw-e365-nu-w875-v1',
    meals: {
      'Breakfast': [
        'Day 1: Scrambled egg whites with spinach and whole-grain toast',
        'Day 2: Greek yogurt with chia seeds and berries',
        'Day 3: Protein smoothie with almond milk and banana',
        'Day 4: Boiled eggs with avocado and tomato slices',
        'Day 5: Oatmeal with a dash of honey and walnuts',
        'Day 6: Cottage cheese with sliced cucumbers and whole-grain crackers',
        'Day 7: Veggie omelette with mushrooms and onions',
      ],
      'Lunch': [
        'Day 1: Grilled chicken salad with olive oil and lemon dressing',
        'Day 2: Steamed fish with broccoli and quinoa',
        'Day 3: Turkey wrap with lettuce and avocado',
        'Day 4: Grilled shrimp with brown rice and asparagus',
        'Day 5: Chicken stir-fry with mixed vegetables',
        'Day 6: Lentil soup with whole-grain bread',
        'Day 7: Grilled salmon with zucchini noodles',
      ],
      'Dinner': [
        'Day 1: Baked cod with roasted vegetables',
        'Day 2: Grilled chicken breast with a side of sweet potato',
        'Day 3: Lean beef patties with sautéed spinach',
        'Day 4: Stir-fried tofu with mushrooms and bok choy',
        'Day 5: Roasted turkey breast with green beans',
        'Day 6: Baked salmon with quinoa pilaf',
        'Day 7: Shrimp and avocado salad with lemon vinaigrette',
      ],
    },
  ),
  MealPlan(
    title: 'Naturally Muscular Meal Plan',
    description: 'Balanced meals with good amounts of protein and carbs.',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1876/4703/files/shutterstock_722297947.jpg?v=1655902970',
    meals: {
      'Breakfast': [
        'Day 1: Whole-grain toast with avocado and poached egg',
        'Day 2: Oatmeal topped with almond butter and fresh fruit',
        'Day 3: Smoothie with spinach, protein powder, and berries',
        'Day 4: Greek yogurt with granola and honey',
        'Day 5: Scrambled eggs with turkey bacon and whole-grain toast',
        'Day 6: Banana pancakes with a side of walnuts',
        'Day 7: Omelette with spinach, feta cheese, and mushrooms',
      ],
      'Lunch': [
        'Day 1: Grilled chicken sandwich with a side salad',
        'Day 2: Brown rice bowl with lean beef and roasted vegetables',
        'Day 3: Grilled salmon with a quinoa salad',
        'Day 4: Turkey wrap with hummus and mixed greens',
        'Day 5: Shrimp stir-fry with basmati rice',
        'Day 6: Grilled chicken Caesar salad with whole-grain croutons',
        'Day 7: Tuna and avocado salad with lemon dressing',
      ],
      'Dinner': [
        'Day 1: Baked chicken thighs with mashed sweet potato',
        'Day 2: Grilled steak with roasted Brussels sprouts',
        'Day 3: Salmon fillet with wild rice and asparagus',
        'Day 4: Lean pork chops with a side of sautéed kale',
        'Day 5: Baked tilapia with a quinoa pilaf',
        'Day 6: Tofu stir-fry with cashews and brown rice',
        'Day 7: Grilled lamb chops with couscous and roasted vegetables',
      ],
    },
  ),
  MealPlan(
    title: 'Lean Build Meal Plan',
    description: 'Higher-calorie meals for muscle growth and energy.',
    imageUrl: 'https://themealprepninja.com/wp-content/uploads/2023/02/Clean-Bulking-Meal-Plan-1080x675.jpg',
    meals: {
      'Breakfast': [
        'Day 1: Whole-grain pancakes with peanut butter and a banana',
        'Day 2: Smoothie with protein powder, oats, and almond milk',
        'Day 3: Scrambled eggs with cheese and whole-grain toast',
        'Day 4: Greek yogurt with mixed nuts and honey',
        'Day 5: Breakfast burrito with eggs, avocado, and black beans',
        'Day 6: Protein waffles with a side of strawberries',
        'Day 7: Overnight oats with chia seeds and almond butter',
      ],
      'Lunch': [
        'Day 1: Grilled chicken pasta with marinara sauce',
        'Day 2: Beef and vegetable stir-fry with jasmine rice',
        'Day 3: Turkey burger with a whole-grain bun and a side salad',
        'Day 4: Baked salmon with a quinoa salad',
        'Day 5: Roasted chicken thighs with mashed potatoes',
        'Day 6: Grilled shrimp tacos with avocado salsa',
        'Day 7: Tuna pasta salad with cherry tomatoes and olive oil',
      ],
      'Dinner': [
        'Day 1: Steak with roasted sweet potatoes and green beans',
        'Day 2: Grilled chicken Alfredo pasta',
        'Day 3: Baked cod with sautéed spinach and wild rice',
        'Day 4: Lean beef meatballs with spaghetti and marinara',
        'Day 5: Roasted turkey breast with cranberry sauce and mashed potatoes',
        'Day 6: Grilled swordfish with quinoa and mixed greens',
        'Day 7: Barbecue pork tenderloin with coleslaw',
      ],
    },
  ),
];
